### ISSUE TITLE
华为手机音频音高设置闪退

### ISSUE THREAD

**Issue by Moriafly** [Moriafly/dirror-music#2]
等待解决

--logversion:utracea
Process Name: &#39;com.dirror.music&#39;
Thread Name: &#39;main&#39;
Back traces starts.
java.lang.NoSuchMethodError: No virtual method getPlaybackParams()Landroid/media/PlaybackParams; in class Landroid/media/MediaPlayer; or its super classes (declaration of &#39;android.media.MediaPlayer&#39; appears in /system/framework/framework.jar)
	at com.dirror.music.service.MusicService$MusicBinder.setPlaybackParams(MusicService.kt:552)
	at com.dirror.music.service.MusicService$MusicBinder.onPrepared(MusicService.kt:319)
	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2533)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5307)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
Back traces ends.

https://blog.csdn.net/xiaxiangnanxp1989/article/details/105660871

**Comment by Moriafly** [comment]
1.6.0c 禁用华为手机设置音高，手上没华为设备，先禁了🤣

**Comment by Moriafly** [comment]
最近未报错误
